name: CLA Check

on:
  pull_request:
    types: [opened, reopened, synchronize]

  workflow_dispatch: # Allow manual trigger
    inputs:
      pull_request_number:
        description: "The number of the pull request to check (only required for manual runs)"
        required: false
        type: string

jobs:
  check-cla:
    runs-on: ubuntu-latest

    steps:
      - name: Check CLA Agreement
        uses: actions/github-script@v6
        with:
          script: |
            const pullRequestNumber = context.payload.pull_request?.number || inputs.pull_request_number;

            if (!pullRequestNumber) {
              core.setFailed(
                "No pull request number found. This workflow can only run on pull_request events or with a pull_request_number input during manual runs."
              );
              return;
            }

            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pullRequestNumber,
            });

            const claSigned = comments.some(comment =>
              comment.body.toLowerCase().includes('i agree to the cla')
            );

            if (!claSigned) {
              core.setFailed(
                "Contributor has not signed the CLA. Please comment 'I agree to the CLA' to proceed."
              );
            }
