name: Run Pytest

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Use a stable major version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Run pip install and capture the output and exit code
          set +e
          output=$(pip install -r requirements.txt 2>&1)
          pip_exit=$?
          echo "$output"
          # Check for the specific error message parts
          if echo "$output" | grep -F "ERROR: Cannot install -r requirements.txt (line 9) and tabulate==0.9.0 because these package versions have conflicting dependencies." >/dev/null && \
             echo "$output" | grep -F "ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts" >/dev/null; then
            echo "Detected the specific dependency conflict error; ignoring."
            exit 0
          else
            exit $pip_exit
          fi

      - name: Run tests
        run: pytest tests/ --junitxml=report.xml  # Removed -x to run all tests

      - name: Upload Test Report
        if: always()  # Ensures the report is uploaded even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: report.xml
